### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by ahmetalpbalkan** [LnxPrgr3/crossfeed#2]
A homebrew formula would be really nice, I'd love to try this with single command.

**Comment by LnxPrgr3** [comment]
This should get you going:

    class Crossfeed < Formula
      homepage "https://github.com/LnxPrgr3/crossfeed"
      url "https://github.com/LnxPrgr3/crossfeed/archive/v1.0.0.tar.gz"
      sha1 "f24473a2739d2b337071e350c76c34275f7e6256"
    
      def install
        system "make"
        mkdir bin
        cp "crossfeed-player", "#{bin}/"
      end
    
      test do
        system "true"
      end
    end

If you save that in /usr/local/Library/Formula/crossfeed.rb (assuming your Homebrew install lives in /usr/local), you should be able to `brew install crossfeed`.
